-- TC008: add missing applicant fields to students table
ALTER TABLE `students`
    ADD COLUMN IF NOT EXISTS `lrn`               VARCHAR(12)  DEFAULT NULL AFTER `student_number`,
    ADD COLUMN IF NOT EXISTS `suffix_name`        VARCHAR(20)  DEFAULT NULL AFTER `middle_name`,
    ADD COLUMN IF NOT EXISTS `place_of_birth`     VARCHAR(200) DEFAULT NULL AFTER `birthdate`,
    ADD COLUMN IF NOT EXISTS `civil_status`       VARCHAR(20)  DEFAULT NULL AFTER `gender`,
    ADD COLUMN IF NOT EXISTS `religion`           VARCHAR(100) DEFAULT NULL AFTER `civil_status`,
    ADD COLUMN IF NOT EXISTS `nationality`        VARCHAR(100) DEFAULT NULL AFTER `religion`,
    ADD COLUMN IF NOT EXISTS `disability`         VARCHAR(200) DEFAULT NULL AFTER `nationality`,
    ADD COLUMN IF NOT EXISTS `perm_region`        VARCHAR(100) DEFAULT NULL AFTER `disability`,
    ADD COLUMN IF NOT EXISTS `perm_province`      VARCHAR(100) DEFAULT NULL AFTER `perm_region`,
    ADD COLUMN IF NOT EXISTS `perm_municipality`  VARCHAR(100) DEFAULT NULL AFTER `perm_province`,
    ADD COLUMN IF NOT EXISTS `perm_barangay`      VARCHAR(100) DEFAULT NULL AFTER `perm_municipality`,
    ADD COLUMN IF NOT EXISTS `perm_address`       TEXT         DEFAULT NULL AFTER `perm_barangay`,
    ADD COLUMN IF NOT EXISTS `perm_zipcode`       VARCHAR(10)  DEFAULT NULL AFTER `perm_address`,
    ADD COLUMN IF NOT EXISTS `mail_region`        VARCHAR(100) DEFAULT NULL AFTER `perm_zipcode`,
    ADD COLUMN IF NOT EXISTS `mail_province`      VARCHAR(100) DEFAULT NULL AFTER `mail_region`,
    ADD COLUMN IF NOT EXISTS `mail_municipality`  VARCHAR(100) DEFAULT NULL AFTER `mail_province`,
    ADD COLUMN IF NOT EXISTS `mail_barangay`      VARCHAR(100) DEFAULT NULL AFTER `mail_municipality`,
    ADD COLUMN IF NOT EXISTS `mail_address`       TEXT         DEFAULT NULL AFTER `mail_barangay`,
    ADD COLUMN IF NOT EXISTS `mail_zipcode`       VARCHAR(10)  DEFAULT NULL AFTER `mail_address`;
